version: '3.8'
services:
  redis:
    image: redis:latest
    command: redis-server
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes: 
      - redis:/var/lib/redis
  api:
    container_name: api 
    restart: unless-stopped
    image: api_prod:1.0.0
    build:
      context: server
      target: server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - redis
  client:
    container_name: client 
    image: client_prod:1.0.0
    environment:
      - VITE_SERVER_URL=http://localhost/api
    build:
      context: client
      target: client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - prod_client:/usr/src/app/dist
    depends_on:
      - redis 
      - api
  nginx:
    image: nginx:1.21.0-alpine
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - prod_client:/usr/share/nginx/html
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
    depends_on:
      - api
      - client
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes: 
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   command: certonly --webroot -w /var/www/certbot --force-renewal --email mail -d domain --agree-tos

volumes:
  redis:
  prod_client:
